### ISSUE TITLE
Cannot add package to an shared project's iOS project

### ISSUE THREAD

**Issue by walkerc4** [zauberzeug/SimpleLocation#1]
Attempting to resolve dependency 'Xamarin.GooglePlayServices (≥ 22.0.0.2)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (≥ 21.0.3.0)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.MediaRouter (≥ 21.0.3.0)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.AppCompat (≥ 22.2.0.0)'.
Adding 'Xamarin.Android.Support.v4 22.2.0.0' to X.App.iOS.

Could not install package 'Xamarin.Android.Support.v4 22.2.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by kaolick** [comment]
I hopefully fixed this issues in version 0.1.1. I was able to add it from the nuget gallery to the iOS project of a test solution. Please give it a try and let me know if it worked.

**Comment by walkerc4** [comment]
Seems fixed, awesome!
